version: '2.0'

services:



 node1.onezone.localhost:
    image: onedata/onezone:3.0.0-RC3
    hostname: node1.onezone.localhost
    # dns: 8.8.8.8 # uncomment if container can't ping any domain
    container_name: onezone-1
    volumes:
        # - "${AUTH_PATH}:/volumes/persistence/var/lib/oz_worker/auth.config"
        - "${ONEZONE_CONFIG_DIR}:/volumes/persistence"
        - "/var/run/docker.sock:/var/run/docker.sock"

  node1.oneprovider.localhost:
    image: onedata/oneprovider:3.0.0-RC3
    hostname: node1.oneprovider.localhost
    # dns: 8.8.8.8 # uncomment if container can't ping any domain
    container_name: oneprovider-1
    volumes:
        - "${ONEPROVIDER_CONFIG_DIR}:/volumes/persistence"
        - "${ONEPROVIDER_DATA_DIR}:/volumes/storage"
        - "/var/run/docker.sock:/var/run/docker.sock"


  oneclient:
    image: onedata/oneclient:3.0.0-RC3
    privileged: true
    # dns: 8.8.8.8 # uncomment if container can't ping any domain
    container_name: oneclient-1
    environment:
      PROVIDER_HOSTNAME: $PROVIDER_HOSTNAME
      ONECLIENT_AUTHORIZATION_TOKEN: $ONECLIENT_AUTHORIZATION_TOKEN
      NO_CHECK_CERTIFICATE: 'true'
