# Oneprovider configuration that will be used by the container

# Configuration of cluster used by Oneprovider
cluster:
  domain_name: "dev.local"
  nodes:
    node:
      hostname: "node"

  manager:
    default_node: "node"
    nodes:
      - "node"
  worker:
    nodes:
      - "node"
  database:
    nodes:
      - "node"

  # Storage backends configiration
  storage:
    # Example of NFS storage configration
    NFS:
      type: "POSIX"
      mount_point: "/mnt/data"

  settings:
    # System process restrictions
    open_files_limit: 65535
    processes_limit: 65535
    # web_certificate: "/root/files/op_web_cert.pem"

oneprovider:
  # Should provider autoamticly try to register with Onezone
  register: true
  # Oneprovider name
  name: "provider"
  # Address that Oneprovider will use when registering with Onezone
  redirection_point: "https://node.dev.local"
  # Geographical coordinates used by user graphical interface
  geo_longitude: 19.945
  geo_latitude: 50.0647

# Onezone configuration that is used by Oneprovider
onezone:
  # Adderess that will be used by Oneprovider to contact Onezone
  domain_name: "onedata.org"
