# oneprovider configuration that will be used by the container

cluster:
  domain_name: "dev.local"
  nodes:
    node:
      hostname: "node"

  manager:
    default_node: "node"
    nodes:
      - "node"
  worker:
    nodes:
      - "node"
  database:
    nodes:
      - "node"

  storage:
    NFS:
      type: "POSIX"
      mount_point: "/mnt/data"

  settings:
    open_files_limit: 65535
    processes_limit: 65535
    web_certificate: "/root/files/op_web_cert.pem"

oneprovider:
  register: true
  name: "provider"
  redirection_point: "https://node.dev.local"
  geo_longitude: 19.945
  geo_latitude: 50.0647

onezone:
  domain_name: "onedata.org"