# onezone configuration that will be used by the container

cluster:
  domain_name: "org"
  nodes:
    node:
      hostname: "onedata"

  manager:
    default_node: "node"
    nodes:
      - "node"
  worker:
    nodes:
      - "node"
  database:
    nodes:
      - "node"

  settings:
    open_files_limit: 65535
    processes_limit: 65535
    web_private_key: "/root/files/oz_web_priv_key.pem"
    web_certificate: "/root/files/oz_web_cert.pem"
    web_ca_certificate: "/root/files/oz_web_ca_cert.pem"
    open_id_auth_config: "/root/files/oz_open_id_auth.config"

onezone:
  name: "example"