# Onezone configuration that will be used by the container

# Configuration of cluster used by Onezone
cluster:
  domain_name: "onedata.org"
  nodes:
    node:
      hostname: "node"

  manager:
    default_node: "node"
    nodes:
      - "node"
  worker:
    nodes:
      - "node"
  database:
    nodes:
      - "node"

  settings:
    # System process restrictions
    open_files_limit: 65535
    processes_limit: 65535
    # Certificates used by Onezone to make https green
    web_private_key: "/root/files/oz_web_priv_key.pem"
    web_certificate: "/root/files/oz_web_cert.pem"
    web_ca_certificate: "/root/files/oz_web_ca_cert.pem"
    open_id_auth_config: "/root/files/oz_open_id_auth.config"

onezone:
  # Pretty name for Onezone to display in graphical user inferface
  name: "example"
