version: '2.0'

services:
  node1.oneprovider.onedata.example.com:
    image: onedata/oneprovider:VFS-2062
    hostname: node1.oneprovider.onedata.example.com
    volumes:
        - "${ONEPROVIDER_CONFIG_DIR}:/volumes/persistency"
        - "${ONEPROVIDER_DATA_DIR}:/volumes/storage"
        - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "53:53"
      - "53:53/udp"
      - "443:443"
      - "80:80"
      - "5555:5555"
      - "5556:5556"
      - "6665:6665"
      - "6666:6666"
      - "8443:8443"
      - "8876:8876"
      - "8877:8877"
      - "9443:9443"
    environment:
      ONEPANEL_BATCH_MODE: "true"
      ONEPROVIDER_CONFIG: |
        cluster:
          domain_name: "oneprovider.onedata.example.com"
          nodes:
            node1:
              hostname: "node1"
          manager:
            default_node: "node1"
            nodes:
              - "node1"
          worker:
            nodes:
              - "node1"
          database:
            nodes:
              - "node1"
          storage:
            NFS:
              type: "POSIX"
              mount_point: "/volumes/storage"
        oneprovider:
          register: true
          name: "example"
          redirection_point: "https://node1.oneprovider.onedata.example.com"
        onezone:
          domain_name: "beta.onedata.org"
