version: '2.0'

services:
  node1.oneprovider.onedata.example.com:
    image: onedata/oneprovider:3.0.0-beta3
    hostname: node1.oneprovider.onedata.example.com
    ports:
      - "80:80"
      - "443:443"
      - "5555:5555"
      - "53:53"      
      - "9443:9443"
      - "8443:8443"
    environment:
      ONEPANEL_BATCH_MODE: "true"
      ONEPROVIDER_CONFIG: |
        cluster:
          domain_name: "oneprovider.onedata.example.com"
          nodes:
            node1:
              hostname: "node1"
          manager:
            default_node: "node1"
            nodes:
              - "node1"
          worker:
            nodes:
              - "node1"
          database:
            nodes:
              - "node1"
          storage:
            NFS:
              type: "POSIX"
              mount_point: "/tmp"
        oneprovider:
          register: true
          name: "example"
          redirection_point: "https://node1.oneprovider.onedata.example.com"
        onezone:
          domain_name: "onedata.org"
