# Scenario description:
# Procinfigured local oneprovider installation.
# OneZone with one, single-node oneprovider.
#
# Example manual run:
# ONEZONE_VERSION=3.0.0.alpha2 ONEPROVIDER_VERSION=3.0.0.alpha2 docker-compose up

version: '2.0'

services:
  onezone:
    image: docker.onedata.org/onezone:${ONEZONE_VERSION}
    restart: always
    hostname: onedata.org
    volumes:
      - "./configs:/root/configs"
      - "./files:/root/files"
    networks:
      - onedata
    environment:
      ONEPANEL_BATCH_MODE: "true"
      ONEPANEL_BATCH_MODE_CONFIG: "/root/configs/onezone.yml"

  oneprovider:
    image: docker.onedata.org/oneprovider:${ONEPROVIDER_VERSION}
    restart: always
    hostname: localhost.localdomain
    volumes:
      - "./configs:/root/configs"
      - "./files:/root/files"
      - "/mnt/data:/mnt/data"
    links:
      - onezone:onedata.org
    networks:
      - oneprovider
    environment:
      ONEPANEL_BATCH_MODE: "true"
      ONEPANEL_BATCH_MODE_CONFIG: "/root/configs/oneprovider.yml"

networks:
  onedata:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK}.0.0/24
          gateway: ${NETWORK}.0.1
          ip_range: ${NETWORK}.0.0/30
  oneprovider:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK}.1.0/24
          gateway: ${NETWORK}.1.1
          ip_range: ${NETWORK}.1.0/30