# Scenario description:
# Procinfigured local oneprovider installation.
# OneZone with one, single-node oneprovider.
#
# Example manual run:
# ONEZONE_VERSION=3.0.0.alpha2 ONEPROVIDER_VERSION=3.0.0.alpha2 docker-compose up

version: '2.0'

services:
  onezone:
    image: docker.onedata.org/onezone:${ONEZONE_VERSION}
    restart: always
    hostname: node.onedata.org
    volumes:
      - "./configs:/root/configs"
      - "./files:/root/files"
    environment:
      ONEPANEL_BATCH_MODE: "true"
      ONEPANEL_BATCH_MODE_CONFIG: "/root/configs/onezone.yml"

  oneprovider:
    image: docker.onedata.org/oneprovider:${ONEPROVIDER_VERSION}
    restart: always
    hostname: node.dev.local
    volumes:
      - "./configs:/root/configs"
      - "./files:/root/files"
      - "/mnt/data:/mnt/data"
    links:
      - onezone:onedata.org
    environment:
      ONEPANEL_BATCH_MODE: "true"
      ONEPANEL_BATCH_MODE_CONFIG: "/root/configs/oneprovider.yml"

  oneclient:
    image: docker.onedata.org/oneclient:${ONECLIENT_VERSION}
    privileged: true
    volumes:
      - "/mnt/data:/mnt/data"
    links:
      - onezone:onedata.org
      - oneprovider:node.dev.local
    environment:
      PROVIDER_HOSTNAME: node.dev.local
      ONECLIENT_AUTHORIZATION_TOKEN: $ONECLIENT_AUTHORIZATION_TOKEN