# Scenario description:
# Single-provider, single-node, required public ip needed to communicate with onedata.org.
# Single oneprovider instance (with its private network).
#
# Example manual run:
# OZ_VERSION=3.0.0.alpha2 OP_VERSION=3.0.0.alpha2 CLIENT_VERSION=3.0.0.alpha.16.g616480e NETWORK=172.30 docker-compose up
version: '2.0'

services:
  op1.node1.localhost.local:
    image: docker.onedata.org/oneprovider:${OP_VERSION}
    restart: always
    hostname: op1.node1.localhost.local
    networks:
      - op1network

networks:
  op1network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK}.1.0/24
          gateway: ${NETWORK}.1.1
          ip_range: ${NETWORK}.1.0/30
