version: '2.0'

services:
  node1.oneprovider.onedata.example.com:
    image: onedata/oneprovider:3.0.0-beta4
    hostname: node1.oneprovider.onedata.example.com
    volumes:
        - "${ONEPROVIDER_CONFIG_DIR}:/data"
    environment:
      ONEPANEL_BATCH_MODE: "true"
      ONEPROVIDER_CONFIG: |
        cluster:
          domain_name: "oneprovider.onedata.example.com"
          nodes:
            node1:
              hostname: "node1"
          manager:
            default_node: "node1"
            nodes:
              - "node1"
          worker:
            nodes:
              - "node1"
          database:
            nodes:
              - "node1"
          storage:
            NFS:
              type: "POSIX"
              mount_point: "/tmp"
        oneprovider:
          register: true
          name: "example"
          redirection_point: "https://node1.oneprovider.onedata.example.com"
        onezone:
          domain_name: "node1.onezone.onedata.example.com"
