version: '2.0'

services:
  node1.onezone.demo.onedata.local:
    image: onedata/onezone:3.0.0-beta3
    hostname: node1.onezone.dev.local
    environment:
      ONEPANEL_BATCH_MODE: "true"
      ONEZONE_CONFIG: |
        cluster:
          domain_name: "onezone.demo.onedata.local"
          nodes:
            node1:
              hostname: "node1"
          manager:
            default_node: "node1"
            nodes:
              - "node1"
          worker:
            nodes:
              - "node1"
          database:
            nodes:
              - "node1"
          settings:
            open_id_auth_config: "https://gist.githubusercontent.com/groundnuty/f05fd4d6d521afd8d9d58f982ffba3c6/raw/61e2da46db9bc4bb6fb4434dcfd58e1e03cfb8d5/oz_open_id_auth.config"
        onezone:
          name: "example"
