version: '2.0'

services:
  node1.oneprovider.localhost:
    image: onedata/oneprovider:3.0.0-rc6
    privileged: true
    hostname: node1.oneprovider.localhost
    # dns: 8.8.8.8 # uncomment if container can't ping any domain
    container_name: oneprovider-1
    volumes:
        - "/sys/fs/cgroup:/sys/fs/cgroup"
        - "/var/run/docker.sock:/var/run/docker.sock"
        # configuration persistence
        - "${ONEPROVIDER_CONFIG_DIR}:/volumes/persistence"
        # data persistence
        - "${ONEPROVIDER_DATA_DIR}:/volumes/storage"
        # Oneprovider
        #- "${OP_PRIV_KEY_PATH}:/volumes/persistence/etc/op_panel/certs/key.pem"
        #- "${OP_CERT_PATH}:/volumes/persistence/etc/op_panel/certs/cert.pem"
        #- "${OP_CACERT_PATH}:/volumes/persistence/etc/op_panel/certs/cacert.pem"
    networks:
      - scenario2
    environment:
      ONEPANEL_BATCH_MODE: "true"
      ONEPROVIDER_CONFIG: |
        cluster:
          domainName: "oneprovider.localhost"
          autoDeploy: true
          nodes:
            n1:
              hostname: "node1"
          managers:
            mainNode: "n1"
            nodes:
              - "n1"
          workers:
            nodes:
              - "n1"
          databases:
            nodes:
              - "n1"
          storages:
            NFS:
              type: "posix"
              mountPoint: "/volumes/storage"
        oneprovider:
          register: true
          name: "Example"
          redirectionPoint: "https://node1.oneprovider.localhost" # OR DOCKER IP ADDRESS
          geoLatitude: ${GEO_LATITUDE}
          geoLongitude: ${GEO_LONGITUDE}
        onezone:
          domainName: "node1.onezone.localhost" # OR DOCKER IP ADDRESS
        onepanel:
          users:
            "admin1":
              password: "Password1"
              userRole: "admin"
            "user1":
              password: "Password2"
              userRole: "regular"

networks:
  scenario2:
