version: '2.0'

services:
  node1.onezone.dev.local:
    image: onedata/onezone:3.0.0-beta3
    hostname: node1.onezone.dev.local
    environment:
      ONEPANEL_BATCH_MODE: "true"
      ONEZONE_CONFIG: |
        cluster:
          domain_name: "onezone.dev.local"
          nodes:
            node1:
              hostname: "node1"
          manager:
            default_node: "node1"
            nodes:
              - "node1"
          worker:
            nodes:
              - "node1"
          database:
            nodes:
              - "node1"
          settings:
            open_id_auth_config: "https://raw.githubusercontent.com/krzysztof-trzepla/onedata-getting-started/develop/files/oz_open_id_auth.config"
        onezone:
          name: "example"
