version: '2.0'

services:
  node1.onezone.localhost:
    image: onedata/onezone:3.0.0-rc6
    privileged: true
    hostname: node1.onezone.localhost
    # dns: 8.8.8.8 # uncomment if container can't ping any domain
    container_name: onezone-1
    volumes:
        - "/sys/fs/cgroup:/sys/fs/cgroup"
        - "/var/run/docker.sock:/var/run/docker.sock"
        # configuration persistance
        - "${ONEZONE_CONFIG_DIR}:/volumes/persistence"
        # OpenId configuration
        #- "${AUTH_PATH}:/volumes/persistence/var/lib/oz_worker/auth.config"
        # DNS configuration
        #- "${DNS_PATH}:/volumes/persistence/var/lib/oz_worker/dns.config"
        # Onepanel
        #- "${OZ_PRIV_KEY_PATH}:/volumes/persistence/etc/oz_panel/certs/key.pem"
        #- "${OZ_CERT_PATH}:/volumes/persistence/etc/oz_panel/certs/cert.pem"
    networks:
      - scenario2
    environment:
      ONEPANEL_BATCH_MODE: "true"
      ONEZONE_CONFIG: |
        cluster:
          domainName: "onezone.localhost"
          autoDeploy: true
          nodes:
            n1:
              hostname: "node1"
          managers:
            mainNode: "n1"
            nodes:
              - "n1"
          workers:
            nodes:
              - "n1"
          databases:
            nodes:
              - "n1"
        onezone:
          name: "Example"
          domainName: "onezone.localhost"
        onepanel:
          users:
            "admin1":
              password: "Password1"
              userRole: "admin"
            "user1":
              password: "Password2"
              userRole: "regular"

networks:
  scenario2:
