version: '2.0'

services:
  node1.onezone.onedata.example.com:
    image: onedata/onezone:3.0.0-beta7
    hostname: node1.onezone.onedata.example.com
    volumes:
        - "${AUTH_PATH}:/volumes/persistency/var/lib/oz_worker/auth.config"
        - "${ONEZONE_CONFIG_DIR}:/volumes/persistency"
        - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "53:53"
      - "53:53/udp"
      - "443:443"
      - "80:80"
      - "5555:5555"
      - "5556:5556"
      - "6665:6665"
      - "6666:6666"
      - "8443:8443"
      - "8876:8876"
      - "8877:8877"
      - "9443:9443"
