version: '2.0'

services:
  node1.oneprovider.onedata.example.com:
    image: onedata/oneprovider:3.0.0-beta5
    hostname: node.localhost.local
    volumes:
        - "${ONEPROVIDER_CONFIG_DIR}:/volumes/persistency"
        - "${ONEPROVIDER_DATA_DIR}:/volumes/storage"
        - "${ONEPROVIDER_APP_CONFIG_PATH}:/volumes/persistency/etc/op_worker/app.config"
        - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "53:53"
      - "53:53/udp"
      - "443:443"
      - "80:80"
      - "5555:5555"
      - "5556:5556"
      - "6665:6665"
      - "6666:6666"
      - "8443:8443"
      - "8876:8876"
      - "8877:8877"
      - "9443:9443"
    extra_hosts:
      - "onedata.example.com:${ONEZONE_IP}"
