version: '2.0'

services:
  node1.oneprovider.onedata.example.com:
    image: onedata/oneprovider:3.0.0-beta4
    hostname: localhost.local
    volumes:
        - "${ONEPROVIDER_CONFIG_DIR}:/tmp/data:"
    ports:
      - "53:53"
      - "80:80"
      - "443:443"
      - "5555:5555"
      - "8443:8443"
      - "8876:8876"
      - "8877:8877"
      - "9443:9443"
    extra_hosts:
      - "onedata.org:${ONEZONE_IP}"
