version: '2.0'

services:
  node1.onezone.onedata.example.com:
    image: onedata/onezone:VFS-2062
    hostname: localhost.local
    ports:
      - "53:53"
      - "80:80"
      - "443:443"
      - "5555:5555"
      - "8443:8443"
      - "8876:8876"
      - "8877:8877"
      - "9443:9443"
    volumes:
        - "${AUTH_PATH}:/data/var/lib/oz_worker/auth.config"