version: '2.0'

services:
  node1.onezone.dev.local:
    image: onedata/onezone:3.0.0-beta3
    hostname: localhost.local
    ports:
      - "53"
      - "80"
      - "443"
      - "5555"
      - "8443"
      - "8876"
      - "8877"
      - "9443"
