version: '2.0'

services:
  node1.onezone.onedata.example.com:
    image: onedata/onezone:3.0.0-beta4
    hostname: node1.onezone.onedata.example.com
    volumes:
        - "${ONEZONE_CONFIG_DIR}:/data"
        - "${AUTH_PATH}:/data/var/lib/oz_worker/auth.config"

  node2.onezone.onedata.example.com:
    image: onedata/onezone:3.0.0-beta4
    hostname: node2.onezone.onedata.example.com
    depends_on:
      - node1.onezone.onedata.example.com
    volumes:
        - "${ONEZONE_CONFIG_DIR}:/tmp/data"
        - "${AUTH_PATH}:/data/var/lib/oz_worker/auth.config"
    environment:
      ONEPANEL_BATCH_MODE: "true"
      ONEZONE_CONFIG: |
        cluster:
          domain_name: "onezone.onedata.example.com"
          nodes:
            node1:
              hostname: "node1"
            node2:
              hostname: "node2"
          manager:
            default_node: "node1"
            nodes:
              - "node1"
          worker:
            nodes:
              - "node1"
          database:
            nodes:
              - "node2"
        onezone:
          name: "example"
