version: '2.0'

services:
  node1.oneprovider.onedata.example.com:
    image: onedata/oneprovider:VFS-2062
    hostname: node.localhost.local
    volumes:
        - "${ONEPROVIDER_CONFIG_DIR}:/volumes/persistency"
        - "${ONEPROVIDER_DATA_DIR}:/volumes/storage"
        - "/var/run/docker.sock:/var/run/docker.sock"
