version: '2.0'

services:
  node1.onezone.onedata.example.com:
    image: onedata/onezone:3.0.0-beta4
    hostname: localhost.local
    volumes:
        - "${ONEZONE_CONFIG_DIR}:/data"
        - "${AUTH_PATH}:/data/var/lib/oz_worker/auth.config"