# Scenario description:
# Procinfigured local oneprovider installation.
# OneZone with one, single-node oneprovider.
#
# Example manual run:
# ONEZONE_VERSION=3.0.0.alpha2 ONEPROVIDER_VERSION=3.0.0.alpha2 docker-compose up

version: '2.0'

services:
  file-server:
    image: nginx
    volumes:
      - "./files:/usr/share/nginx/html:ro"

  onezone:
    image: docker.onedata.org/onezone:${ONEZONE_VERSION}
    restart: always
    privileged: true
    hostname: node1.onedata.org
    links:
      - file-server:file-server
    environment:
      ONEPANEL_BATCH_MODE: 'true'
      ONEZONE_CONFIG: |
        cluster:
          domain_name: "onedata.org"
          nodes:
            node:
              hostname: "node1"
          manager:
            default_node: "node"
            nodes:
              - "node"
          worker:
            nodes:
              - "node"
          database:
            nodes:
              - "node"
          settings:
            open_files_limit: 65535
            processes_limit: 65535
            web_private_key: "http://file-server/oz_web_priv_key.pem"
            web_certificate: "http://file-server/oz_web_cert.pem"
            web_ca_certificate: "http://file-server/oz_web_ca_cert.pem"
            open_id_auth_config: "http://file-server/oz_open_id_auth.config"
        onezone:
          name: "example"

  node1.oneprovider:
    image: docker.onedata.org/oneprovider:${ONEPROVIDER_VERSION}
    restart: always
    privileged: true
    hostname: node1.dev.local
    volumes:
      - "/mnt/data:/mnt/data"
    links:
      - onezone:onedata.org
      - file-server:file-server

  node2.oneprovider:
    image: docker.onedata.org/oneprovider:${ONEPROVIDER_VERSION}
    restart: always
    privileged: true
    hostname: node2.dev.local
    volumes:
      - "/mnt/data:/mnt/data"
    links:
      - onezone:onedata.org
      - file-server:file-server
      - node1.oneprovider:node1.dev.local
    environment:
      ONEPANEL_BATCH_MODE: 'true'
      ONEPROVIDER_CONFIG: |
        cluster:
          domain_name: "dev.local"
          nodes:
            node1:
              hostname: "node1"
            node2:
              hostname: "node2"
          manager:
            default_node: "node2"
            nodes:
              - "node2"
          worker:
            nodes:
              - "node2"
          database:
            nodes:
              - "node1"
          storage:
            NFS:
              type: "POSIX"
              mount_point: "/mnt/data"
          settings:
            open_files_limit: 65535
            processes_limit: 65535
            web_certificate: "http://file-server/op_web_cert.pem"
        oneprovider:
          register: true
          name: "provider"
          geo_longitude: 19.945
          geo_latitude: 50.0647
        onezone:
          domain_name: "onedata.org"
